# Generated by Django 3.2.6 on 2021-10-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210906_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kakoid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedbacks',
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=300)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.feedback')),
            ],
            options={
                'db_table': 'feedback_images',
            },
        ),
    ]
