# Generated by Django 3.2.6 on 2022-01-04 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_admin_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('30c943c4-12c2-418b-8ea5-57a80a15508b'), editable=False),
        ),
    ]
