# Generated by Django 3.2.6 on 2021-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAIL_OPR_ISTT_CD', models.CharField(max_length=20)),
                ('RAIL_OPR_ISTT_NM', models.CharField(max_length=20)),
                ('LN_CD', models.CharField(max_length=20)),
                ('LN_NM', models.CharField(max_length=20)),
                ('STIN_CD', models.CharField(max_length=20)),
                ('STIN_NM', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
